### ISSUE TITLE
Create a new logo for logo.h

### ISSUE THREAD

**Issue by idreamsi** [adafruit/Adafruit_PixelDust#1]
Hi
Thanks for share this fantastic project, My question is:
1. How to add another logo
2. And how the Adafruit logo is made (What tool has been made.)

I tested different **Bitmap to Array tools** but failed.

Thanks.

**Comment by kolasinski** [comment]
I've just asked tech support the same ecact question. If/when i get a reply i will comment bavk to you.  Roger

**Comment by porrey** [comment]
This is a great project and a lot of work obviously went into this. I built this device and wanted my own images as well. I figured out how to read an image using C# and converting it into a color array that I could then user to set the pixels. I eventually turned this into an application. If you are interested in how  to convert images take a look at the code. If just want to create images for the device you can download and run the application in Visual Studio. The code is available at [**https://github.com/porrey/ledmatrixide**](https://github.com/porrey/ledmatrixide).

**Comment by ladyada** [comment]
@porrey yay that sounds great, can you submit a PR that adds a link/instructions to the README in this repo?

**Comment by ladyada** [comment]
@porrey to the rescue! closing now that we have it in the readme :)
